steps:
options:
  logging: CLOUD_LOGGING_ONLY

  # Build container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', '.']
  # Push container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend']
  # Deploy container image to Cloud Run
- name: gcr.io/cloud-builders/gcloud
  args: ['beta',
            'run',
            'deploy',
            'backend',
            '--image',
            'gcr.io/$PROJECT_ID/backend',
            '--region',
            'asia-southeast2',
            '--platform',
            'managed',
            '--allow-unauthenticated']
images:
  - 'gcr.io/$PROJECT_ID/backend'