steps:
  # Build container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/models', '.']
  # Push container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/models']
  # Deploy container image to Cloud Run
- name: gcr.io/cloud-builders/gcloud
  args: [   'run',
            'deploy',
            'models',
            '--image=gcr.io/$PROJECT_ID/models',
            '--region=asia-southeast2',
            '--platform=managed',
            '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/models'